---
# maintains versions and can overwrite all.yml
avail:
  snapshot_url: https://snapshots.publicnode.com/avail-2710711.tar.lz4
  validator:
    version: v2.3.4.1
    grandpa_authority_id: "0xf8ed0036a12280086a4fa0a122287c94f134410c11d3c27745c6bf6d402625a3"
    node:
      version: v18.20.5

vara:
  snapshot_url: https://snapshots.vara.network/vara-mainnet-31499599.tar.lz4
  validator:
    version: v1.10.0
    grandpa_authority_id: "0x394ad066ec16ed8902a178450944403d1576243a154eafdb35341977668bfefc"
    node:
      version: v18.20.5
