---
node_ufw_rules:
  validator:
    - port: "{{ avail[type].ports.p2p_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: p2p_port

    - port: "{{ avail[type].ports.prometheus_port }}"
      proto: tcp
      rule: allow
      from: "{{ monitor_server_dns }}"
      comment: prometheus_port

  fullnode:
    - port: "{{ avail[type].ports.p2p_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: p2p_port

    - port: "{{ avail[type].ports.prometheus_port }}"
      proto: tcp
      rule: allow
      from: "{{ monitor_server_dns }}"
      comment: prometheus_port

    - port: "{{ avail[type].ports.rpc_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: rpc_port
