---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:

    avail:
      hosts:
        validator.avail.testnet.encapsulate.xyz:
          type: validator
          db_dir: "/opt/avail/data/chains/avail_turing_network/db"
