---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:

    avail:
      hosts:
        validator.avail.testnet.encapsulate.xyz:
          type: validator
