---
- name: Stop service
  ansible.builtin.systemd:
    name: "{{ service_identifier }}"
    state: stopped

- name: Delete data folder
  ansible.builtin.file:
    path: "{{ db_dir }}"
    state: absent

- name: Create data directory
  ansible.builtin.file:
    path: "{{ db_dir }}"
    state: directory
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0755"

- name: Download and Extract lz4 format snapshot
  ansible.builtin.shell: |
    set -o pipefail
    curl -o - -L {{ snapshot_url | default(vars[project].snapshot_url) }} | lz4 -c -d - | tar -x -C {{ db_dir }}
  async: 10000
  poll: 10
  args:
    executable: /bin/bash
    creates: "{{ db_dir }}"

- name: Set ownership for data directory
  ansible.builtin.file:
    path: "{{ db_dir }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    recurse: true

- name: Restart service
  ansible.builtin.systemd:
    name: "{{ service_identifier }}"
    state: restarted
